### ISSUE TITLE
Add support for `_test` suffix

### ISSUE THREAD

**Issue by leandrolcampos** [guidorice/mojo-pytest#6]
Is it possible to add support for the `_test` suffix? In this case, a file whose name ends with `_test.mojo` or  `_test.🔥` would also be collected.

**Comment by guidorice** [comment]
Hey @leandrolcampos good suggestion, I will add that. That would also match [pytest test discovery](https://docs.pytest.org/en/7.2.x/explanation/goodpractices.html#test-discovery) more closely.

**Comment by guidorice** [comment]
@leandrolcampos please give a try and see if it's working for you. 🎉

**Comment by leandrolcampos** [comment]
Hi, @guidorice! Thanks a lot!
